<?php
/**
 * Listado Comunas de Chile por Regiones
 * @link       https://marketingrapel.cl
 * @since      1.0.0
 * @package    wc-ciudades-y-regiones-de-chile
 * @subpackage wc-ciudades-y-regiones-de-chile/places
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */
 
global $places;

$places['CL'] = array(
	'CL-AP' => array(
        'Arica',
        'Camarones',
        'General Lagos',
        'Putre'
	),
	'CL-TA' => array(
        'Alto Hospicio' => 'Alto Hospicio',
        'Camiña' => 'Camiña',
        'Colchane' => 'Colchane',
        'Huara' => 'Huara',
        'Iquique' => 'Iquique',
        'Pica' => 'Pica',
        'Pozo Almonte' => 'Pozo Almonte',
	),
	'CL-AN' => array(
        'Antofagasta',
        'Calama',
        'María Elena',
        'Mejillones',
        'Ollagüe',
        'San Pedro de Atacama',
        'Sierra Gorda',
        'Taltal',
        'Tocopilla'
	),
	'CL-AT' => array(
        'Alto del Carmen',
        'Caldera',
        'Chañaral',
        'Copiapó',
        'Diego de Almagro',
        'Freirina',
        'Huasco',
        'Tierra Amarilla',
        'Vallenar'
	),
	'CL-CO' => array(
        'Andacollo',
		'Canela',
		'Combarbalá',
		'Coquimbo',
		'Illapel',
		'La Higuera',
		'La Serena',
		'Los Vilos',
		'Monte Patria',
		'Ovalle',
		'Paihuano',
		'Punitaqui',
		'Río Hurtado',
		'Salamanca',
		'Vicuña'
	),
	'CL-VS' => array(
        'Algarrobo',
		'Cabildo',
		'Calera',
		'Calle Larga',
		'Cartagena',
		'Casablanca',
		'Catemu',
		'Concón',
		'El Quisco',
		'El Tabo',
		'Hijuelas',
		'Isla de Pascua',
		'Juan Fernández',
		'La Cruz',
		'La Ligua',
		'Limache',
		'Llaillay',
		'Los Andes',
		'Nogales',
		'Olmué',
		'Panquehue',
		'Papudo',
		'Petorca',
		'Puchuncaví',
		'Putaendo',
		'Quillota',
		'Quilpué',
		'Quinteros',
		'Rinconada',
		'San Antonio',
		'San Esteban',
		'San Felipe',
		'Santa María',
		'Santo Domingo',
		'Valparaíso',
		'Villa Alemana',
		'Viña del Mar',
		'Zapallar'
	),
	'CL-RM' => array(
        'Alhué',
		'Buín',
		'Calera de Tango',
		'Cerrillos',
		'Cerro Navia',
		'Colina',
		'Conchalí',
		'Curacaví',
		'El Bosque',
		'El Monte',
		'Estación Central',
		'Huechuraba',
		'Independencia',
		'Isla de Maipo',
		'La Cisterna',
		'La Florida',
		'La Granja',
		'La Pintana',
		'La Reina',
		'Lampa',
		'Las Condes',
		'Lo Barnechea',
		'Lo Espejo',
		'Lo Prado',
		'Macul',
		'Maipú',
		'María Pinto',
		'Melipilla',
		'Ñuñoa',
		'Padre Hurtado',
		'Paine',
		'Pedro Aguirre Cerda',
		'Peñaflor',
		'Peñalolén',
		'Pirque',
		'Providencia',
		'Pudahuel',
		'Puente Alto',
		'Quilicura',
		'Quinta Normal',
		'Recoleta',
		'Renca',
		'San Bernardo',
		'San Joaquín',
		'San José de Maipo',
		'San Miguel',
		'San Pedro',
		'San Ramón',
		'Santiago',
		'Talagante',
		'Tiltil',
		'Vitacura'
	),
	'CL-LI' => array(
        'Chépica',
		'Chimbarongo',
		'Codegua',
		'Coinco',
		'Coltauco',
		'Doñihue',
		'Graneros',
		'La Estrella',
		'Las Cabras',
		'Litueche',
		'Lolol',
		'Machalí',
		'Malloa',
		'Marchihue',
		'Mostazal',
		'Nancagua',
		'Navidad',
		'Olivar',
		'Paredones',
		'Palmilla',
		'Peralillo',
		'Peumo',
		'Pichidegua',
		'Pichilemu',
		'Placilla',
		'Pumanque',
		'Quinta de Tilcoco',
		'Rancagua',
		'Rengo',
		'Requínoa',
		'San Fernando',
		'San Vicente',
		'Santa Cruz'
	),
	'CL-ML' => array(
        'Cauquenes',
		'Chanco',
		'Colbún',
		'Constitución',
		'Curepto',
		'Curicó',
		'Empedrado',
		'Hualañé',
		'Licantén',
		'Linares',
		'Longaví',
		'Maule',
		'Molina',
		'Parral',
		'Pelarco',
		'Pelluhue',
		'Pencahue',
		'Rauco',
		'Retiro',
		'Río Claro',
		'Romeral',
		'Sagrada Familia',
		'San Clemente',
		'San Javier',
		'San Rafael',
		'Talca',
		'Teno',
		'Vichuquén',
		'Villa Alegre',
		'Yerbas Buenas'
	),
	'CL-NB' => array(
        'Bulnes',
		'Chillán',
		'Chillán Viejo',
		'Cobquecura',
		'Coelemu',
		'Coihueco',
		'El Carmen',
		'Ninhue',
		'Ñiquén',
		'Pemuco',
		'Pinto',
		'Portezuelo',
		'Quillón',
		'Quirihue',
		'Ranqui',
		'San Carlos',
		'San Fabián de Alico',
		'San Ignacio',
		'San Nicolás',
		'Treguaco',
		'Yungay'
	),
	'CL-BI' => array(
        'Alto Biobío',
		'Antuco',
		'Arauco',
		'Cabrero',
		'Cañete',
		'Chiguayante',
		'Concepción',
		'Contulmo',
		'Coronel',
		'Curanilahue',
		'Florida',
		'Hualpén',
		'Hualquí',
		'Laja',
		'Lebu',
		'Los Álamos',
		'Los Ángeles',
		'Lota',
		'Mulchén',
		'Nacimiento',
		'Negrete',
		'Penco',
		'Quilaco',
		'Quilleco',
		'San Pedro de La Paz',
		'San Rosendo',
		'Santa Bárbara',
		'Santa Juana',
		'Talcahuano',
		'Tirúa',
		'Tomé',
		'Tucapel',
		'Yumbel'
	),
	'CL-AR' => array(
        'Angol',
		'Carahue',
		'CholChol',
		'Collipulli',
		'Cunco',
		'Curacautín',
		'Curarrehue',
		'Ercilla',
		'Freire',
		'Galvarino',
		'Gorbea',
		'Lautaro',
		'Loncoche',
		'Lonquimay',
		'Los Sauces',
		'Lumaco',
		'Melipeuco',
		'Nueva Imperial',
		'Padre las Casas',
		'Perquenco',
		'Pitrufquén',
		'Pucón',
		'Purén',
		'Renaico',
		'Saavedra',
		'Temuco',
		'Teodoro Schmidt',
		'Toltén',
		'Traiguén',
		'Victoria',
		'Vilcún',
		'Villarrica'
	),
	'CL-LR' => array(
        'Corral',
		'Futrono',
		'La Unión',
		'Lago Ranco',
		'Lanco',
		'Los Lago',
		'Máfil',
		'Mariquina',
		'Paillaco',
		'Panquipulli',
		'Río Bueno',
		'Valdivia'
	),
	'CL-LL' => array(
        'Ancud',
		'Calbuco',
		'Castro',
		'Chaitén',
		'Chonchi',
		'Cochamó',
		'Curaco de Veléz',
		'Dalcahue',
		'Fresia',
		'Frutillar',
		'Futaleufú',
		'Hualaihue',
		'Llanquihue',
		'Los Muermos',
		'Maullín',
		'Osorno',
		'Palena',
		'Puerto Montt',
		'Puerto Octay',
		'Puerto Varas',
		'Puqueldón',
		'Purranque',
		'Puyehue',
		'Queilén',
		'Quellón',
		'Quemchi',
		'Quinchao',
		'Río Negro',
		'San Juan de la Costa',
		'San Pablo'
	),
	'CL-AI' => array(
        'Aisén',
		'Chile Chico',
		'Cisnes',
		'Cochrane',
		'Coyhaique',
		'Guaitecas',
		'Lago Verde',
		'O\'Higgins',
		'Río Ibáñez',
		'Tortel'
	),
	'CL-MA' => array(
        'Antártica',
		'Puerto Williams',
		'Laguna Blanca',
		'Puerto Natales',
		'Porvenir',
		'Primavera',
		'Punta Arenas',
		'Río Verde',
		'San Gregorio',
		'Timaukel',
		'Torres del Paine'
	)	
);